---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: libraryservice-%%BUILD_NUMBER%%
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: libraryservice
        version: %%BUILD_NUMBER%%
      annotations:
        prometheus.io/scrape: true
    spec:
      containers:
      - name: details
        image: localhost:5000/library-service:%%BUILD_NUMBER%%
        imagePullPolicy: IfNotPresent
        ports:
        - name: libraryservice-api
          containerPort: 8080
        env:
        - name: GO_ARGS
          value: -version=%%BUILD_NUMBER%%